name: Deploy Prod
on:
    push:
        branches: [master]

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 12.x
              uses: actions/setup-node@v1
              with:
                  node-version: 12.x

            - name: Set up SSH
              run: |
                  mkdir -p ~/.ssh/
                  echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
                  sudo chmod 600 ~/.ssh/id_rsa
                  echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
              shell: bash
              env:
                  SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
                  SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}

            - name: Install Yarn/PM2
              run: npm install -g yarn pm2

            - name: Deploy
              run: yarn deploy:prod
              env:
                  SECRET: ${{secrets.SECRET}}
                  HSD_API_KEY: ${{secrets.HSD_API_KEY}}
                  TELEGRAM: ${{secrets.TELEGRAM}}
                  TWITTER_CONSUMER_KEY: ${{secrets.TWITTER_CONSUMER_KEY}}
                  TWITTER_CONSUMER_SECRET: ${{secrets.TWITTER_CONSUMER_SECRET}}
                  TWITTER_ACCESS_TOKEN_KEY: ${{secrets.TWITTER_ACCESS_TOKEN_KEY}}
                  TWITTER_ACCESS_TOKEN_SECRET: ${{secrets.TWITTER_ACCESS_TOKEN_SECRET}}
